apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: nip-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nginx.192.168.122.237.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: nip-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nip-demo
  labels:
    app: nginx-demo
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nip-demo
spec:
  selector:
    app: nginx-demo
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
