apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 5m
  releaseName: harbor
  targetNamespace: harbor
  chart:
    spec:
      chart: harbor
      version: "2.1.*"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  install:
    createNamespace: true
  values:
    expose:
      type: ingress
      ingress:
        hosts:
          core: harbor.example.com
    externalURL: https://harbor.example.com
