apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: system
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/william-barros-costa/portfolio_devops
  ref:
    branch: main
  
