apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  releaseName: 
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: "1.18.*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
  values:
     # 1) Use host network so it binds directly to node port 80/443
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      # 2) Pin it to a specific node (e.g. master) or your “ingress node”
      nodeSelector:
        kubernetes.io/hostname: master   # <-- adjust to your node name/label

      # 3) Tolerate control-plane taints so it can run on master if needed
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"

      # (optional) Service type is irrelevant with hostNetwork, but you can
      # keep it as ClusterIP or NodePort; it just won’t be used for external traffic
      service:
        type: ClusterIP
